export const icons = {
    arrowback: require("../../assets/icons/arrow-left.png"),
    arrowdown: require("../../assets/icons/arrow-down.png"),
    eyeshow: require("../../assets/icons/eye-show.png"),
    google: require("../../assets/icons/google.png"),
    searchbtn: require("../../assets/icons/search-btn.png"),
    searchbtncircle: require("../../assets/icons/search-btn-circle.png"),
    checkboxfilluncheck: require("../../assets/icons/checkbox-fill-uncheck.png"),
    checkboxfillcheck: require("../../assets/icons/checkbox-fill-check.png"),
    distance: require("../../assets/icons/distance.png"),
    filterbtncircle: require("../../assets/icons/filter-btn-circle.png"),
    location: require("../../assets/icons/location.png"),
    calendar: require("../../assets/icons/calendar.png"),
    profilecircle: require("../../assets/icons/profile-circle.png"),
    chat: require("../../assets/icons/chat.png"),
    plans: require("../../assets/icons/plans.png"),
    profile: require("../../assets/icons/profile.png"),
    home: require("../../assets/icons/home.png"),
    logout: require("../../assets/icons/logout.png"),
    edit: require("../../assets/icons/edit.png"),
    calendarcolor: require("../../assets/icons/calendar-color.png"),
    locationcolor: require("../../assets/icons/location-color.png"),
    profilecirclecolor: require("../../assets/icons/profile-circle-color.png"),
}